# Generated by Django 4.2.5 on 2023-09-10 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=128, verbose_name='Street')),
                ('zip_code', models.CharField(max_length=5, verbose_name='Zip code')),
                ('city', models.CharField(max_length=64, verbose_name='City')),
                ('country', models.CharField(max_length=64, verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Article name')),
                ('sku', models.CharField(max_length=12, verbose_name='Stock Keeping Unit (SKU)')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Price')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Carrier name')),
            ],
            options={
                'verbose_name': 'Carrier name',
                'verbose_name_plural': 'Carrier names',
            },
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=64, verbose_name='Tracking number')),
                ('status', models.CharField(choices=[('none', 'None'), ('in-transit', 'in-transit'), ('transit', 'transit'), ('inbound-scan', 'inbound-scan'), ('scanned', 'scanned'), ('delivery', 'delivery')], default='none', max_length=12, verbose_name='Status')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carriers', to='shipment_app.carrier', verbose_name='Carrier')),
                ('receiver_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_address', to='shipment_app.address', verbose_name='Receiver address')),
                ('sender_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_address', to='shipment_app.address', verbose_name='Sender address')),
            ],
            options={
                'verbose_name': 'Tracking',
                'verbose_name_plural': 'Tracking',
            },
        ),
        migrations.CreateModel(
            name='TrackingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Quantity')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='shipment_app.article', verbose_name='Article')),
                ('tracking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_list', to='shipment_app.tracking', verbose_name='Tracking')),
            ],
            options={
                'verbose_name': 'Tracking Item',
                'verbose_name_plural': 'Tracking Items',
            },
        ),
    ]
