# Generated by Django 4.2.5 on 2023-09-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Carrier name'),
        ),
    ]
