# Generated by Django 4.2.5 on 2023-09-11 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipment_app', '0002_alter_carrier_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=5, unique=True, verbose_name='Zip code'),
        ),
        migrations.AlterField(
            model_name='article',
            name='sku',
            field=models.CharField(max_length=12, unique=True, verbose_name='Stock Keeping Unit (SKU)'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='tracking_number',
            field=models.CharField(max_length=64, unique=True, verbose_name='Tracking number'),
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coord_lon', models.FloatField(blank=True, null=True, verbose_name='Longitude of the location')),
                ('coord_lat', models.FloatField(blank=True, null=True, verbose_name='Latitude of the location')),
                ('weather_id', models.IntegerField(blank=True, null=True, verbose_name='Weather condition id')),
                ('weather_main', models.CharField(blank=True, max_length=64, null=True, verbose_name='Group of weather parameters (Rain, Snow, Clouds etc.)')),
                ('weather_description', models.CharField(blank=True, max_length=128, null=True, verbose_name='Weather condition within the group')),
                ('main_temp', models.FloatField(blank=True, null=True, verbose_name='Temperature')),
                ('main_feels_like', models.FloatField(blank=True, null=True, verbose_name='Temperature feels like')),
                ('main_pressure', models.FloatField(blank=True, null=True, verbose_name='Atmospheric pressure on the sea level')),
                ('main_humidity', models.FloatField(blank=True, null=True, verbose_name='Humidity')),
                ('main_temp_min', models.FloatField(blank=True, null=True, verbose_name='Minimum temperature at the moment')),
                ('main_temp_max', models.FloatField(blank=True, null=True, verbose_name='Maximum temperature at the moment')),
                ('main_sea_level', models.FloatField(blank=True, null=True, verbose_name='Atmospheric pressure on the sea level')),
                ('main_grnd_level', models.FloatField(blank=True, null=True, verbose_name='Atmospheric pressure on the ground level')),
                ('visibility', models.IntegerField(blank=True, null=True, verbose_name='Visibility, meter')),
                ('wind_speed', models.FloatField(blank=True, null=True, verbose_name='Wind speed')),
                ('wind_deg', models.FloatField(blank=True, null=True, verbose_name='Wind direction')),
                ('wind_gust', models.FloatField(blank=True, null=True, verbose_name='Wind gust')),
                ('clouds_all', models.IntegerField(blank=True, null=True, verbose_name='Cloudiness')),
                ('rain_1h', models.FloatField(blank=True, null=True, verbose_name='Rain volume for the last 1 hour')),
                ('rain_3h', models.FloatField(blank=True, null=True, verbose_name='Rain volume for the last 3 hours')),
                ('dt', models.DateTimeField(blank=True, null=True, verbose_name='Time of data calculation, unix, UTC ')),
                ('sys_country', models.CharField(blank=True, max_length=4, null=True, verbose_name='Country code')),
                ('sys_sunrise', models.DateTimeField(blank=True, null=True, verbose_name='Sunrise time, unix, UTC')),
                ('sys_sunset', models.DateTimeField(blank=True, null=True, verbose_name='Sunset time, unix, UTC')),
                ('timezone', models.DateTimeField(blank=True, null=True, verbose_name='Shift in seconds from UTC')),
                ('city_id', models.SmallIntegerField(blank=True, null=True, verbose_name='City ID')),
                ('city_name', models.CharField(blank=True, max_length=4, null=True, verbose_name='City name')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='addresses', to='shipment_app.address', verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Current weather',
                'verbose_name_plural': 'Current weather list',
            },
        ),
    ]
