# Generated by Django 4.2.5 on 2023-09-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment_app', '0003_alter_address_zip_code_alter_article_sku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='city_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='City ID'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='city_name',
            field=models.CharField(blank=True, max_length=48, null=True, verbose_name='City name'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='clouds_all',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cloudiness'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='visibility',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Visibility, meter'),
        ),
    ]
