# Generated by Django 4.2.5 on 2023-09-11 15:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shipment_app', '0004_alter_weather_city_id_alter_weather_city_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
