# Generated by Django 4.2.5 on 2023-09-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment_app', '0005_weather_created_at_weather_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='weather_main',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Group of weather parameters'),
        ),
    ]
